### ISSUE TITLE
我想用这个开发一个智能营销的系统

### ISSUE THREAD

**Issue by Sabirjan** [zhaoyingjun/chatbot#10]
现在遇到的问题是 
（1）会话管理 ，主流程 和多个副流程    主流程是主要介绍和受理业务的  副流程是  回答用户的各种各样的问题的。。。
这个能实现吗

**Comment by zhaoyingjun** [comment]
这样看的话 主流程是不需要用NLP来做的，直接就可以枚举出来了，或者做个规则匹配就没有问题，因为内容都是静态的。你所描述的副流程实现起来没有问题的，但是要想达到好的想过，建议提高训练语料的质量和专业性。7月份开始，是有定制化服务可以提供的，如有需要可以联系我。
