### ISSUE TITLE
tf2版seq2seq报错 ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Saturn24** [zhaoyingjun/chatbot#107]
File "F:/chatbot/chatbot/chineseChatbotWeb-tf2.0/seq2seqChatbot/execute.py", line 54, in <module>
    input_tensor,input_token,target_tensor,target_token= read_data(gConfig['seq_data'], gConfig['max_train_data_size'])
  File "F:/chatbot/chatbot/chineseChatbotWeb-tf2.0/seq2seqChatbot/execute.py", line 37, in read_data
    input_lang,target_lang=create_dataset(path,num_examples)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by tf302** [comment]
同问

**Comment by OnlyBrownAnt** [comment]
文件有问题或者路径错误。我这边是发现小黄鸭语料库文件内容是空的，自己重新去找小黄鸭语料库下载替换上去。然后错误解决

**Comment by woshinigege1** [comment]
换了词库也没用，还是报同样的错误

**Comment by zhaoyingjun** [comment]
ValueError: not enough values to unpack (expected 2, got 1) 这个是文件路径的问题，确认一下文件是否存在

**Comment by Terio2020** [comment]
还有个可能，我碰到的；我是换成自己的小语料库，由于语料库太小了，出现这个问题。
在seq2seq.ini中修改相应的max_train_data_size的值，让其小一点就可以训练了。具体多少可能要自己尝试

**Comment by xzmlove** [comment]
有人解决了这个问题吗？

**Comment by thanhsang298** [comment]
The line: input_lang, target_lang = zip(*word_pairs) in data_util.py seem raise ValueError: not enough values ​​to unpack (expected 2, got 1).
Has anyone solved this problem? Thank you
