### ISSUE TITLE
訓練出來的ckpt.data及ckpt.meta大小都固定是正常嗎?

### ISSUE THREAD

**Issue by o55665516** [zhaoyingjun/chatbot#12]
您好，我執行execute.py之後，不管我的train.enc跟train.dec有多少對話筆數
訓練出來的seq2seq.ckpt容量都一樣，這是正常的嗎~還是有設定只取前幾筆對話，導致訓練出來的模型大小都一樣?

**Comment by zhaoyingjun** [comment]
都一样是多大？ 不应该都一样的

**Comment by o55665516** [comment]
目前我這個從step0到現在，data都固定71365KB，meta都39960KB
![default](https://user-images.githubusercontent.com/11363415/44127362-92cb9e68-a06f-11e8-9507-1b19d1974875.PNG)

另一個之前訓練的已經step八萬多，容量也都一樣
![2](https://user-images.githubusercontent.com/11363415/44127391-b19cfd82-a06f-11e8-85fb-40a998cfadac.PNG)

但可以看出兩個的train.dec並不一樣大小，而且正常data跟meta應該會越來越多才對吧~~
