### ISSUE TITLE
訓練出來的ckpt.data及ckpt.meta大小都固定是正常嗎?

### ISSUE THREAD

**Issue by o55665516** [zhaoyingjun/chatbot#13]
目前我這個從step0到現在，data都固定71365KB，meta都39960KB

![default](https://user-images.githubusercontent.com/11363415/44130690-520cd07e-a081-11e8-80d0-43e282b87a65.PNG)

另一個之前訓練的已經step八萬多，容量也都一樣

![2](https://user-images.githubusercontent.com/11363415/44130698-55d4e1e2-a081-11e8-8ae0-a86624e381b8.PNG)

但可以看出兩個的train.dec並不一樣大小，而且正常data跟meta應該會越來越多才對吧~~
會是因為seq2seq_serve.ini有個max_train_data_size值設定50000的關係嗎?

**Comment by zhaoyingjun** [comment]
mac_train_data_size设置的是读取训练集的发小，你的preplxy有在下降吗

**Comment by zhaoyingjun** [comment]
prelexity在下降就可以

**Comment by o55665516** [comment]
一開始
global step 2100 learning rate 0.5000 step-time 0.52 perplexity 151.84
現在
global step 18000 learning rate 0.4950 step-time 0.65 perplexity 1.30
看起來下降滿多的，但是容量都固定就覺得有點怪~

另外想請教一下，要訓練多久或是step到達多少才會訓練結束
