### ISSUE TITLE
pytorch版本，执行execute出现错误

### ISSUE THREAD

**Issue by Seanqwq** [zhaoyingjun/chatbot#136]
![{TVFJ1%I3TZ0SP3% MHUS)A](https://user-images.githubusercontent.com/108247305/175852909-032dd375-1d0d-4170-a0f3-5ac32555bdf3.png)

**Comment by Seanqwq** [comment]
能帮忙看看是什么原因吗

**Comment by chensisi0730** [comment]
问题解决了吗

**Comment by chensisi0730** [comment]
@Seanqwq
