### ISSUE TITLE
需要訓練多久?perplexity 多少算正常?

### ISSUE THREAD

**Issue by o55665516** [zhaoyingjun/chatbot#14]
一開始
global step 2100 learning rate 0.5000 step-time 0.52 perplexity 151.84
現在
global step 18000 learning rate 0.4950 step-time 0.65 perplexity 1.30
看起來下降滿多的，但是容量都固定就覺得有點怪~
想請教perplexity 要多少才算合理?

另外想請教 @zhaoyingjun 一下，要訓練多久或是step到達多少才會訓練結束?
感謝~

**Comment by zhaoyingjun** [comment]
perplexity  接近1就可以了，最好的是等于1
