### ISSUE TITLE
执行 execute.py 时报TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by scorpionGT** [zhaoyingjun/chatbot#15]
请问下，每次在create_model下到model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)这步时，就会TypeError: can't pickle _thread.RLock objects，请问有遇到过吗？如何解决的呢？

**Comment by zhaoyingjun** [comment]
没有遇到过，你的TF版本是多少？

**Comment by scorpionGT** [comment]
我用的是1.9的，试过降到1.2也是一样会报那个错

**Comment by zhaoyingjun** [comment]
README里有的，1.0.1
