### ISSUE TITLE
perplexity接近1，但回答都重複

### ISSUE THREAD

**Issue by o55665516** [zhaoyingjun/chatbot#16]
不好意思，想再請問一下
我訓練大概step到十萬左右，perplexity都很接近1了，大概1.0X
但執行app.py之後的回覆句子都會是同一兩句(非預設的''^_^'')
請問這個原因可能是什麼?

**Comment by scorpionGT** [comment]
你好，我想请问你的tf用的是多少版本的？你那边有遇到这个错吗：TypeError: can't pickle _thread.RLock objects

**Comment by zhaoyingjun** [comment]
你应该没有把字典数量给调高，训练的样本集不够，过拟合了，因为有分词 所以建议把字典调到10万以上

**Comment by o55665516** [comment]
字典數是指seq2seq.ini中的max_train_data_size嗎
