### ISSUE TITLE
训练结果出现大量unk

### ISSUE THREAD

**Issue by ericosmic** [zhaoyingjun/chatbot#21]
你好，我在使用默认的训练集进行训练，大概进行了14000steps后（preprlexity<10）后，对话质量好像很差，而且出现大量unk符号，按照建议我已经将enc_vocab_size和dec_vocab_size加大到100000，但好像没有改善。 我不知道问题处在哪。

**Comment by ericosmic** [comment]
@zhaoyingjun   0-10 bucket 一开始一直为空，后来把bucket0 的范围调整为（5-10）才开始有数据变化。最好的时候 bucket0 大概是80， bucket 1 大概80 多，bucket2 大概 150， bucket3 大概200

**Comment by lixuan1** [comment]
> 你好，我在使用默认的训练集进行训练，大概进行了14000steps后（preprlexity<10）后，对话质量好像很差，而且出现大量unk符号，按照建议我已经将enc_vocab_size和dec_vocab_size加大到100000，但好像没有改善。 我不知道问题处在哪。

你好，你的问题解决了吗，我有同样的问题

**Comment by lixuan1** [comment]
> 你的桶的preprlexity是多少？

总的preprlexity是在1附近时，bucket0是empty,bucket1,2,3的preprlexity是很大的数字，是过拟合了吗,

**Comment by zhaoyingjun** [comment]
调整一下bucket各个桶的的语句长度

**Comment by lixuan1** [comment]
> 调整一下bucket各个桶的的语句长度

噢，好的，谢谢，我尝试一下
另外那个seqGAN版本的disc_data是漏传了吗？没有那个没法进行字典的生成？
