### ISSUE TITLE
训练效果不佳，求解

### ISSUE THREAD

**Issue by tomwenthey** [zhaoyingjun/chatbot#23]
按照建议将词典大小增加到100000，然后用自带语料库训练后出现大量UNK，后来自己找了小黄鸡语料，perplexity降到了3左右就基本不下降了，但是回答的效果很差，没有任何逻辑，我想问下是为什么...语料的问题吗？

**Comment by lixuan1** [comment]
> 你看一下进行词向量转换后的是不是有很多3 就是unk，如果是则需要继续调大词典的size

词向量转换后不是大量的3,是正常的数字，但是训练出来回复都是^_^

**Comment by zhaoyingjun** [comment]
perplexity 是多少？ 如果是用的这里面提供的训练集的最好的效果也不是很好，因为训练集的质量太差，你可以打开训练看一下。可以更换一下高质量的训练集

**Comment by lixuan1** [comment]
> perplexity 是多少？ 如果是用的这里面提供的训练集的最好的效果也不是很好，因为训练集的质量太差，你可以打开训练看一下。可以更换一下高质量的训练集

总的perplexity是1点多，但bucket1,2,3的很大，大概分别是几千，几万，十几万这样子，正常吗
