### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by JoinChang** [zhaoyingjun/chatbot#30]
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: ./gen_data/train.answer : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3`

执行 seqGanChatbot\execute.py 时报此错误

**Comment by zhaoyingjun** [comment]
文件不存在造成的
