### ISSUE TITLE
[seqGanChatbot] 調用 gen_pre_train()時，報錯

### ISSUE THREAD

**Issue by DavidLanz** [zhaoyingjun/chatbot#31]
一開始，是於utils/data_util.py中，vocab_file.write(w + "\n")這一行報錯，顯示bytes不能與字串"\n"連結在一起存檔，所以修改為vocab_file.write(str(w) + "\n")順利儲存gen_data/train.answer、train.query，test.query，以及test.answer四個檔案，接著，執行execute.py 在  # step_1 training gen model，調用 gen_pre_train()時，報錯(有產生在gen_data路徑下vocab2500.all，有64.6KB)，報錯所以終止執行，錯誤訊息如下：File "/seqGanChatbot/utils/data_utils.py", line 52, in basic_tokenizer，查找後，發現words.extend(re.split(_WORD_SPLIT, space_separated_fragment))這行，會丟出: cannot use a bytes pattern on a string-like object例外，再看gen_data/vocab2500.all裡，確實都是存成了 b'\xe5\x9c\x9f'這樣的bytes換行符號，能否請您協助查看呢? 感謝!!

**Comment by zhaoyingjun** [comment]
这个是编码的问题

**Comment by tectal** [comment]
能不能将seqgan写个说明doc呢？

**Comment by yuxuan2015** [comment]
@DavidLanz  Has your problem been solved?

**Comment by DavidLanz** [comment]
nope, not yet.

**Comment by zhaoyingjun** [comment]
b'\xe5\x9c\x9f' 这个是因为编码使用错了，你使用的是utf-8吗？ 你看一下繁体中文的编码，因为我用的都是简体中文，所以没有使用过繁体中文训练
