### ISSUE TITLE
训练效果的问题

### ISSUE THREAD

**Issue by NexusLee** [zhaoyingjun/chatbot#36]
enc_vocab_size = 100000
dec_vocab_size = 100000
max_train_data_size = 200000

我在训练50w步后大概接近 1.1这样，但发现回答效果还是重复，中间有续训，请问是还要提高词向量大小吗，还是我中间出了什么问题

**Comment by NexusLee** [comment]
刚翻了issue，发现bucket好像不对
global step 550500 learning rate 0.0331 step-time 0.22 perplexity 1.08
  eval: empty bucket 0
  eval: bucket 1 perplexity 365178.56
  eval: bucket 2 perplexity 810757.55
  eval: bucket 3 perplexity 931497.51

**Comment by niliusha123** [comment]
请问，您解决了bucket为0的问题了吗？

**Comment by zhaoyingjun** [comment]
是的 ，你这buckety都已经飞上天了 你的已经完全过拟合了
