### ISSUE TITLE
seqGan资源缺失了

### ISSUE THREAD

**Issue by LiuShaohan** [zhaoyingjun/chatbot#37]
目录中并无以下资源：
    train_enc = "./gen_data/train.query"
    train_dec = "./gen_data/train.answer"
    test_enc =  "./gen_data/test.query"
    test_dec =  "./gen_data/test.answer"
    resource_data = "./data_source/conv.txt"

**Comment by zhaoyingjun** [comment]
conv.txt是原始资源，忘记上传，其他的都是自动生成的

**Comment by LiuShaohan** [comment]
谢谢，已经run了。
