### ISSUE TITLE
seqGAN，execute.py出现list index out of range的问题, 

### ISSUE THREAD

**Issue by niliusha123** [zhaoyingjun/chatbot#38]
您好，我训练seqGAN中的模型，出现下面的结果和错误，请问这应该如何解决，谢谢

- ==================Update Discriminator: 199=====================
- ==============================mc_search:False===================================
- ==================Update Generator: 199=========================
- =============================mc_search:True====================================

这里的Discriminator出现的结果总是False，同时，报以下的错误

 

- File "execute.py", line 198, in al_train
-     print(" ".join([tf.compat.as_str(rev_vocab[output]) for output in train_answer[i]]))
-   File "execute.py", line 198, in <listcomp>
-     print(" ".join([tf.compat.as_str(rev_vocab[output]) for output in train_answer[i]]))
- IndexError: list index out of range

请问，这是哪里出现了问题，谢谢

**Comment by zhaoyingjun** [comment]
你的output的数值 超过了rev_vocab的长度，你看一下你的设置，是不是train_answer的长度太大了
