### ISSUE TITLE
训练完模型，该如何在服务器上测试

### ISSUE THREAD

**Issue by niliusha123** [zhaoyingjun/chatbot#39]
@zhaoyingjun , hi ,您好，我也训练完后，在服务器测试，结果如下，

- Serving Flask app "app" (lazy loading)
- Environment: production
- WARNING: Do not use the development server in a production environment.
- Use a production WSGI server instead.
- Debug mode: off
- Running on http://12.12.12.12:1080/ (Press CTRL+C to quit)

然后在浏览器打不开http://12.12.12.12:1080/，请问这个怎么解决的

- 上面的12.12.12.12地址代替了我自己的服务器地址

**Comment by zhaoyingjun** [comment]
你端口用1080？ 这个端口容易被占用的，你看一下是不是端口冲突了，建议选用8080以上的端口
