### ISSUE TITLE
heartbeat issue

### ISSUE THREAD

**Issue by visayang2005** [zhaoyingjun/chatbot#4]
hi，我跑你代码execute.py时，跑完后显示：
####################
Mode : train

Preparing data in working_dir
working_dir/train.enc 词汇表大小: 20000
working_dir/train.dec 词汇表大小: 20000
对话转向量...
对话转向量...
对话转向量...
对话转向量...
Creating 3 layers of 256 units.
Created model with fresh parameters.
Killed
############################
然后我执行根目录下的app.py, 结果一直显示heartbeat，每分钟显示一天，都显示了5个小时了
2018-03-06 22:36:23 - heartbeat
2018-03-06 22:37:23 - heartbeat
2018-03-06 22:38:23 - heartbeat
2018-03-06 22:39:23 - heartbeat
2018-03-06 22:40:23 - heartbeat

请问这是正常的吗？我是继续等待还是需要修改什么地方？

**Comment by zhaoyingjun** [comment]
这个是应用啊，是个心跳检测机制。训练的话是要跑execute.py，你看一下你的内存，你这个进程被你的机器给杀了，等跑完execute.py之后，再跑可视化系统app.py
