### ISSUE TITLE
应用场景问题

### ISSUE THREAD

**Issue by cfl2005** [zhaoyingjun/chatbot#40]
您好：
   想问一下seq2seq用来做问答系统，与KBQA相比效果如何呢？目前在做问答系统的选型工作，KBQA对问答库的依赖比较大，等于是基于分词去进行检索，个人并不看好这种方式。所以还请您指点一下，谢谢！

**Comment by zhaoyingjun** [comment]
总体上来说还是建议seq2seq，如果是要保证问答的专业性尤其是对于专业术语要去比较高的话，KBQA也可以，就是那种严苛的法律条款式的问答
