### ISSUE TITLE
请问如何制作自己的语料库

### ISSUE THREAD

**Issue by limitzhou** [zhaoyingjun/chatbot#42]
想基于自己的FAQ材料，制作成适合咱们使用的语料库，请问使用何种工具可以制作？

**Comment by zhaoyingjun** [comment]
你把你的语料按照一问一答的方式存在txt文档里 注意文档的编码，然后用data_util进行语料的处理即可。

**Comment by zhaoyingjun** [comment]
如果有疑问或者需要帮助可以qq联系我934389697
