### ISSUE TITLE
欢迎交流

### ISSUE THREAD

**Issue by chenmoshushi** [zhaoyingjun/chatbot#43]
试验了下，web界面真心不错，效果真烂

**Comment by chenmoshushi** [comment]
有些怀疑作者有没有训练出好的结果，敢不敢也上传下你训练的模型

**Comment by zhaoyingjun** [comment]
如果你想要提高训练效果，可以以问题的方式提出来，我有时间的话可以告诉你提高训练效果的方法。项目是我开源的，但是我并没有义务保证你直接下载下来就能够跑出好结果。请你在你的本地删除我的代码，以免忽悠了你。不要被拿来主义害了自己。

**Comment by chenmoshushi** [comment]
这么多issue,没看到一个解决了的，全都被你closed，我可以删除你的代码，也请你关闭的你项目，浪费别人时间，骗钱还不说，还误人子弟

**Comment by zhaoyingjun** [comment]
你把我给气笑了兄弟，你是不是不懂编程啊，还是刚入门来做的，你有没有看到issue里有多少是因为编码错误问题提出的，编码问题给出解决办法了还不算解决吗。。。，按照你的逻辑，你大可以去tensorflow开源项目下开一个issue，要求tensorflow项目自己关闭了，因为你没有学会tensorflow编程，他们这是误人子弟。

**Comment by chenmoshushi** [comment]
github开源是好的，然而人家多少大项目也没在readme里面弄个付费链接的博客呀，关键想要赚钱收费也可以理解，好歹也弄的像点样子啊，不是界面好就行的，代码里面问题那么多，随便个seq2seq效果比你的强吧，咱也要对得起项目的star数对不对，不要让其他外国的朋友冲着这么多star进来，结果发现代码效果跟屎一样，还跑不通。期待能未来有点真的干货，多给人惊喜而不是失望。

**Comment by zhaoyingjun** [comment]
你有没有想过一个你自己都不愿意承认的事实，就是所有下载这个项目的人员只有你幻想着找个项目fork一下，下载下来，然后直接几行命令跑起来了，还能得到自己想要的效果。至于付费博客，这是项目开源之后很久才写的，觉得这个内容写的比较详细可能对大家有帮助，但是如果直接把内容贴出来又不符合与平台的约定，所以放了个链接。一共才5元钱，想赚钱谁会用这种没效率的方式赚钱。也别扯国外的朋友，国外的朋友也用不起来，因为这是中文聊天机器人。至于干货，对于拿来主义的人在开源项目上没有干货可言，因为永远想的是不劳而获。至于训练的效果问题，神经网络靠的调参和特征优化，还有训练语料的质量，如果你一条都不会凭什么能够训练处好的效果。
