### ISSUE TITLE
回答语句出现乱码

### ISSUE THREAD

**Issue by XingyuXiong** [zhaoyingjun/chatbot#46]
您好，我在ubuntu18.04虚拟机下通过了训练，运行，访问服务器后出现对应界面，发送语句后得到了这样的乱码 ç  ® å ¾  å ¹ ² ä º 
请问应该如何解决？

**Comment by zhaoyingjun** [comment]
是编码的问题，你看一下ubuntu18.04是不是没有安装中文字体包

**Comment by XingyuXiong** [comment]
之前确实没有。现在我在language support里安装了中文包且可以输入中文了，依然显示乱码

**Comment by zhaoyingjun** [comment]
你看一下你train.enc还有voc中的文字是不是乱码的

**Comment by XingyuXiong** [comment]
是的，train.enc全是乱码，voc除了前四个词__PAD__ __GO__ __EOS__ __UNK__全是乱码

**Comment by zhaoyingjun** [comment]
删除这些文件，重新生成 用data_utils
