### ISSUE TITLE
作者您好，tf2版本的使用过程中遇到了一些问题。不知道这个问题该如何去解决，能指点一下吗？

### ISSUE THREAD

**Issue by nickbob1996** [zhaoyingjun/chatbot#69]
我在训练过程中已经生成模型，保存模型了。于是我想要把模型拿出来看看效果，就使用了predict函数  ，具体代码是:
q = precit("你好，你叫什么名字呢？")
print(q)
结果就提示我
![QQ截图20200306132227](https://user-images.githubusercontent.com/58163440/76055122-b0e4ff80-5fad-11ea-93a0-9cb98292d8ef.jpg)
这个问题是出在哪儿了呢，才给我报这种nonetype的错。我学习深度学习的时间不太久，多多包涵卅，期待您的回复！

**Comment by nickbob1996** [comment]
![1](https://user-images.githubusercontent.com/58163440/76055391-74fe6a00-5fae-11ea-8176-a9e39e388324.jpg)
![2](https://user-images.githubusercontent.com/58163440/76055396-7760c400-5fae-11ea-8fef-0e337ea2dc21.jpg)

**Comment by zhaoyingjun** [comment]
你对比一下 为什么app.py中不出现这个问题。关于为什么nonype 建议要勤百度

**Comment by nickbob1996** [comment]
> 你对比一下为什么app.py中不出现这个问题。关于为什么nonype建议要勤百度
好的 多谢
