### ISSUE TITLE
已经训练完成，但是要怎么在本地运行起来呢

### ISSUE THREAD

**Issue by Saligia** [zhaoyingjun/chatbot#7]
我想看看训练效果，直接执行./webui/app.py会打不开0.0.0.0:8080。因为没有使用服务器的经验，希望您能告知一下。

**Comment by zhaoyingjun** [comment]
你的8080是不是被占用了，看一下app.py的最后一行，那里有访问地址的配置

**Comment by Saligia** [comment]
谢谢，已经能够运行了，但是一直回复我^_^。我训练第二次了，但是复杂度一直降不下去，请问有已经训练好的模型给我参考一下比较好的训练结果是怎样的吗？

**Comment by Saligia** [comment]
我看到您提示的增加分词后要修改词典大小了，请问多大比较合适呢？我再重新训练一次。

**Comment by zhaoyingjun** [comment]
5万 或者10万吧

**Comment by niliusha123** [comment]
@Saligia , hi ,您好，我也训练完后，在服务器测试，结果如下，

- * Serving Flask app "app" (lazy loading)
-  * Environment: production
-    WARNING: Do not use the development server in a production environment.
-    Use a production WSGI server instead.
-  * Debug mode: off
-  * Running on http://172.17.0.5:1080/ (Press CTRL+C to quit)

然后在浏览器打不开http://172.17.0.5:1080/，请问您是怎么解决的

**Comment by niliusha123** [comment]
@Saligia , hi ,您好，我也训练完后，在服务器测试，结果如下，

Serving Flask app "app" (lazy loading)
Environment: production
WARNING: Do not use the development server in a production environment.
Use a production WSGI server instead.
Debug mode: off
Running on http://*.*.*.*:1080/ (Press CTRL+C to quit)
然后在浏览器打不开http://*.*.*.*:1080/，请问您是怎么解决的

**Comment by niliusha123** [comment]
@Saligia , hi ,您好，我也训练完后，在服务器测试，结果如下，

- Serving Flask app "app" (lazy loading)
- Environment: production
- WARNING: Do not use the development server in a production environment.
- Use a production WSGI server instead.
- Debug mode: off
- Running on http://12.12.12.12:1080/ (Press CTRL+C to quit)

然后在浏览器打不开http://12.12.12.12:1080/，请问您是怎么解决的

- 上面的12.12.12.12地址代替了我自己的服务器地址
